services:
  - type: web
    name: lotto-predictor
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn -k uvicorn.workers.UvicornWorker -w 2 -t 120 server_render:app"
    autoDeploy: true
